FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
RUN pip install streamlit requests pandas

# Copiar frontend
COPY frontend/ ./frontend/

# Exponer puerto
EXPOSE 8501

# Comando para ejecutar frontend
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
